### ISSUE TITLE
Change dataframes in vemamodelling to xarray and apply pint

### ISSUE THREAD

**Issue by lujakockritz** [imagepbl/image-materials#74]
Subtasks

- [ ] specify dimensions for xarray to align with type, region, time, fuel @RoelBrouwer 
- [ ] adapting inflow_outflow_dynamic_np to process xarray - substep of #15 
- [ ] ensure correct unit application with pint
- [ ] ensure correct labelling of DataFrames #60 
- [ ] move xarray conversion to preprocessing
- [x] add requirements.txt #8
